name: Build & Upload Python Package

env:
  PyPiToken: ${{ secrets.PYPI_API_TOKEN }}

on:
  push:
    branches:
      - development

jobs:
  Install-Build:
    name: Install dependencies & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Generate Build
        run: |
          python -m pip install build
          python -m build --sdist --wheel --outdir dist/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  Publish:
    name: Publish on PyPi
    runs-on: ubuntu-latest
    needs: Install-Build
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish distribution to PyPI
        env:
          TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # This will be used as a fallback for token
        run: |
          pip install twine
          twine upload dist/*