name: Upload Python Package

on:
  push:
    branches:
      - development
      
env:
  PyPiToken: ${{ secrets.PYPI_API_TOKEN }}

jobs:
  Install-Build:
    name: Install dependencies & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Generate Build
        run: |
          python -m pip install build
          python -m build --sdist --wheel --outdir dist/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  Publish:
    name: Publish on PyPi
    runs-on: ubuntu-latest
    needs: Install-Build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          user: __token__
          password: ${{ env.PyPiToken }}