name: Upload Python Package

on:
  push:
    branches:
      - development
      
env:
  PyPiToken: ${{ secrets.PYPI_API_TOKEN }}

jobs:
  Install:
    name: Install Python & Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install build
        run: python -m pip install build

  Build:
    name: Build Distribution
    runs-on: ubuntu-latest
    needs: Install
    steps:
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/

  Publish:
    name: Publish on PyPi
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ env.PyPiToken }}